### ISSUE TITLE
Feature Request: spaceleader without which-key

### ISSUE THREAD

**Issue by jgarte** [mohkale/spaceleader#1]
Hi,

Would it be possible to support spaceleader without which-key?

**Comment by mohkale** [comment]
Hi,

Yes. This should be possible and supported out of the box. We only really depend on 2 which-key functions and we explicitly only run them after which-key has been loaded. Are you unable to use spaceleader without which-key? Could you share any backtraces or exceptions if this is the case.

**Comment by jgarte** [comment]
Thanks for the reply,

> supported out of the box. 

Via a `defcustom` variable?

What's your recommended way to turn `which-key` off?

**Comment by mohkale** [comment]
No I mean you shouldn't have to do anything. If you don't have witch-key installed, spaceleader won't do anything space-key related.

**Comment by jgarte** [comment]
> spaceleader won't do anything space-key related.

Do you mean that spaceleader won't do anything `which-key` related? 

So, it just binds the functions to keys and defaults to not using the which-key menu? Did I understand that correctly?

If I package spaceleader for [guix](guix.gnu.org), for example, I'd have to create a modified guix package of spaceleader with the which-key package removed from the inputs. I think it would be easier if `which-key` could just be turned off by configuring an option variable with `setq`. 

wdyt?

Here's a guix package for spaceleader:

https://git.sr.ht/~whereiseveryone/guixrus/tree/master/item/guixrus/packages/emacs.scm#L2600

**Comment by mohkale** [comment]
@jgarte 

> Do you mean that spaceleader won't do anything which-key related?
> So, it just binds the functions to keys and defaults to not using the which-key menu? Did I understand that correctly?

Yes. That's pretty much how it is atm.

> If I package spaceleader for [guix](https://github.com/mohkale/spaceleader/issues/guix.gnu.org), for example, I'd have to create a modified guix package of spaceleader with the which-key package removed from the inputs

We do however depend on bind-key, dash, general and bind-map. Some of those might be out of date at this point but we definitely depend on general and bind-map. You can see dependencies in a packages [package-requires line](https://github.com/mohkale/spaceleader/blob/5e27c7c517f60beaf2bd2446957aec0ce55e11fe/spaceleader.el#L24).

**Comment by jgarte** [comment]
Should `which-key` be added to the [package-requires line](https://github.com/mohkale/spaceleader/blob/5e27c7c517f60beaf2bd2446957aec0ce55e11fe/spaceleader.el#L24)?

**Comment by mohkale** [comment]
No, since it's optional. Anything which-key related will only happen after which-key is required. If which-key isn't loaded (such as when it isn't installed) then everything else should keep working as is.

**Comment by fbievan** [comment]
This should probably be closed
